### ISSUE TITLE
Внедрить паттерн PageObject

### ISSUE THREAD

**Issue by AnastasiaKorol** [dmpl/AbbyyAutomationTests#2]
Нужно до конца внедрить паттерн PageObject. Сравните ваши тесты и, например, вот эти http://www.protesting.ru/automation/practice/pageobject_selenium.html. PageObject предполагает, что вся логика работы со страницей скрыта в классе страницы, тесты не работают напрямую с элементами.

**Comment by dmpl** [comment]
Перенёс всю логику работы с элементами в классы страниц
